import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const file = new URL('../../../qa/browser-fixture.json', import.meta.url);
const fixture = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file)) : null;
const field = (page, label) => page.locator('form label').filter({ hasText: label }).locator('..').locator('input,select').first();

test('purchase and sales returns use named selections and preserve invalid entries', async ({ page }) => {
  test.skip(!fixture, 'Create disposable browser fixtures first.');
  test.setTimeout(120000);
  page.setDefaultTimeout(15000);
  await page.goto('/');
  await page.locator('#email').fill(fixture.email);
  await page.locator('#password').fill(fixture.password);
  await page.getByRole('button', { name: /sign in/i }).click();
  await expect(page.locator('#email')).toHaveCount(0);
  const api = async (method, path, data) => {
    const res = await page.request.fetch('/api/backend/' + path, { method, data });
    expect(res.ok(), await res.text()).toBeTruthy();
    return res.json();
  };
  const tag = String(Date.now());
  const customerResult = await api('POST', 'customers', { name: 'Return Customer ' + tag, customer_number: 'RC-' + tag });
  const customer = customerResult.data || customerResult;
  await api('POST', 'vendors', { name: 'Return Supplier ' + tag, vendor_number: 'RV-' + tag });
  await page.goto('/products');
  await page.getByRole('button', { name: 'Add New', exact: true }).click();
  await page.getByPlaceholder('Product name').fill('Return Item ' + tag);
  await page.getByPlaceholder('SKU', { exact: true }).fill('RP-' + tag);
  await field(page, /^Costing Price$/).fill('100');
  await field(page, /^Opening Quantity$/).fill('10');
  await page.locator('form label').filter({ hasText: /^Warehouse/ }).locator('..').getByRole('combobox').click();
  await page.getByText('QA Warehouse', { exact: true }).last().click();
  const productResponse = page.waitForResponse(r => /\/products(?:\?|$)/.test(r.url()) && r.request().method() === 'POST');
  await page.locator('form button[type="submit"]').click();
  expect((await productResponse).status()).toBe(201);
  const products = await api('GET', 'products');
  const product = products.data.find(p => p.sku === 'RP-' + tag);

  await page.goto('/purchases');
  await page.getByRole('button', { name: 'Purchase Returns', exact: true }).click();
  await page.getByRole('button', { name: 'New Purchase Return', exact: true }).click();
  await page.getByLabel('Supplier', { exact: true }).selectOption({ label: 'Return Supplier ' + tag });
  await page.getByLabel('Return Number').fill('PR-' + tag);
  await page.getByLabel('Warehouse', { exact: true }).selectOption(String(fixture.warehouse_id));
  await page.getByLabel('Product', { exact: true }).selectOption(String(product.id));
  await page.getByLabel('Quantity', { exact: true }).fill('2');
  const savedPurchase = page.waitForResponse(r => r.url().endsWith('/purchase-returns') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save Purchase Return' }).click();
  const purchaseResponse = await savedPurchase;
  expect(purchaseResponse.status(), await purchaseResponse.text()).toBe(201);
  expect(purchaseResponse.request().headers()['idempotency-key']).toBeTruthy();
  await expect(page.getByText('PR-' + tag, { exact: true })).toBeVisible();
  expect(Number((await api('GET', 'products/' + product.id)).current_stock_in_base_uom)).toBe(8);

  const detailResponse = await api('GET', 'products/' + product.id);
  const detail = detailResponse.data || detailResponse;
  const uom = product.product_uoms?.[0];
  expect(uom, JSON.stringify(detail)).toBeTruthy();
  await api('POST', 'sales-invoices', { customer_id: customer.id, invoice_no: 'SI-' + tag, invoice_date: '2026-01-10', warehouse_id: fixture.warehouse_id, vat_mode: 'exclusive', items: [{ product_id: product.id, sale_uom_id: uom.id, price_uom_id: uom.id, quantity: 2, unit_price: 200 }] });
  await page.goto('/sales/returns');
  await page.getByRole('button', { name: 'New Return', exact: true }).click();
  await field(page, /^Customer$/).selectOption(String(customer.id));
  await page.getByLabel('Source Invoice').selectOption({ label: 'SI-' + tag });
  await page.getByLabel('Invoice Item', { exact: true }).selectOption({ label: 'Return Item ' + tag + ' - invoiced quantity 2' });
  await field(page, /^Qty$/).fill('1');
  const savedSale = page.waitForResponse(r => r.url().endsWith('/sales-returns') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save Return', exact: true }).click();
  const saleResponse = await savedSale;
  expect(saleResponse.status(), await saleResponse.text()).toBe(201);
  await expect(page.locator('form')).toHaveCount(0);
  expect(Number((await api('GET', 'products/' + product.id)).current_stock_in_base_uom)).toBe(7);
  await page.getByRole('button', { name: 'New Return', exact: true }).click();
  await field(page, /^Customer$/).selectOption(String(customer.id));
  await page.getByLabel('Source Invoice').selectOption({ label: 'SI-' + tag });
  await page.getByLabel('Invoice Item', { exact: true }).selectOption({ label: 'Return Item ' + tag + ' - invoiced quantity 2' });
  await field(page, /^Qty$/).fill('2');
  await page.getByRole('button', { name: 'Save Return', exact: true }).click();
  await expect(page.locator('p[role="alert"]')).toContainText('Return quantity exceeds');
  await expect(field(page, /^Qty$/)).toHaveValue('2');
  await page.screenshot({ path: '../qa/return-validation.png', fullPage: true });
  await page.goto('/purchases/new');
  await page.locator('#vendor').click();
  await page.getByRole('option', { name: 'Return Supplier ' + tag, exact: true }).click();
  const row = page.locator('tbody tr').first();
  await row.getByRole('combobox').first().click();
  await page.getByRole('option', { name: 'Return Item ' + tag, exact: true }).click();
  const draftSaved = page.waitForResponse(r => /\/purchase-bills(?:\?|$)/.test(r.url()) && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Save as Draft', exact: true }).click();
  const draft = await draftSaved;
  expect(draft.status(), await draft.text()).toBe(201);
  const draftBody = await draft.json();
  expect((draftBody.data || draftBody).status).toBe('draft');
  expect(Number((await api('GET', 'products/' + product.id)).current_stock_in_base_uom)).toBe(7);
});
